---
- name: Ansible Playbook to Install and Setup Apache on Ubuntu #User-defined name
  hosts: webservers #Specifies the target hosts
  become: yes #Enable privilege escalation
  vars_prompt:
    - name: common_name
      prompt: "192.168.53.3"
      private: no

  tasks: #List of tasks to be executed on target hosts
    - name: INSTALL APACHE2
      apt: name=apache2 update_cache=yes state=latest
 
    - name: ENABLED MOD_REWRITE
      apache2_module: name=rewrite state=present
      notify:
        - RESTART APACHE2
    
    - name: Copy index test page
      template:
        src: "index.html.j2"
        dest: "/var/www/html/index.html"

    - name: Enable SSL module
      apache2_module:
        name: ssl
        state: present

    - name: Generate self-signed certificate
      command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt
      args:
        creates: /etc/ssl/private/apache-selfsigned.key

    - name: Enable SSL virtual host
      command: a2ensite default-ssl.conf
      args:
        warn: no
      notify:
        - Restart Apache2

    - name: Find process ID using port 443
      command: lsof -t -i :443
      register: process_id
      ignore_errors: true

    - name: Kill process using port 443
      shell: "kill -9 {{ process_id.stdout }}"
      when: process_id.stdout is defined

  handlers:
    - name: Restart Apache2
      service: name=apache2 state=restarted 
